### ISSUE TITLE
Some strings can't be translated

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1003]
- Quit
- About Fedistar
- m h s d y (post duration 4m, 24s 5d 1y)
- column width
- column sizes xs md etc...

v. 1.5.2

**Comment by tassoman** [comment]
Schedule calendar isn't translated, months and weekdays are English.

**Comment by h3poteto** [comment]
"Column width" is already prepared. Please translate it on Crowdin.

**Comment by tassoman** [comment]
Italian translation was updated
