### ISSUE TITLE
weird time counter

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1004]
![immagine](https://github.com/h3poteto/fedistar/assets/92727/9f72af3f-5f59-4242-b016-ce287ff66587)

Time counter, go home, you're drunk  🥴  🤣  🤌

**Comment by h3poteto** [comment]
This is a rare occurrence with Fediverse shipping orders. Do you have steps to reproduce?

**Comment by tassoman** [comment]
Just open the timeline column,  you'll find statuses published more than 60 seconds ago, and more than 60 minutes ago.

I expected they were published at most 60s ago then 1min .
At most 60 min ago, then 1 hour

**Comment by h3poteto** [comment]
I can't find it. My timeline works fine.
![Screenshot from 2023-07-22-10-18-53](https://github.com/h3poteto/fedistar/assets/4631959/130b96f1-a1b7-484a-b275-59da6a2886ba)

**Comment by tassoman** [comment]
88s is non sense, in our culture we use to count to 60sec then 2min

![immagine](https://github.com/h3poteto/fedistar/assets/92727/6ef2d33e-7c18-482f-bf30-24d5d344c500)

Also this is confusing, a day is made of 24h, should be 2d

**Comment by h3poteto** [comment]
Whether 88s should be displayed as 2min or 1min is a difficult question. This is determined by the dayjs library. 

And I think it is not so a big problem. I'm not going to change this behavior.

**Comment by tassoman** [comment]
To me 88s is 60 < 88s < 120s = 2 minutes.  When you go after 120 it's 3 mins. :shrug:

**Comment by tassoman** [comment]
Fixed in 1.7.1
