### ISSUE TITLE
Japanese text is rendered with a simplified Chinese font using Chinese glyph variants in the Japanese locale (macOS)

### ISSUE THREAD

**Issue by knu** [h3poteto/fedistar#1007]
I'm not sure if it's only on macOS, but this is what I get:
<img width="343" alt="スクリーンショット 2023-07-20 19 25 22" src="https://github.com/h3poteto/fedistar/assets/10236/4a184c30-16fa-4927-99ea-e601853c83c6">
cf. https://heistak.github.io/your-code-displays-japanese-wrong/

Below is what I expect it to be, a screenshot of Mastodon web rendered by a popular browser:
<img width="349" alt="スクリーンショット 2023-07-20 19 29 52" src="https://github.com/h3poteto/fedistar/assets/10236/34ebd0bc-20a0-4683-9e95-a8119fb1bc2d">

It would be great if you could tweak the font-family specification via settings.

**Comment by knu** [comment]
Thanks, just confirmed it all looks good in v1.5.4.

I'm starting to worry about Chinese speaking users.  I just hope they can use fedistar with an appropriate `lang=”zh-…”` attribute value set.

**Comment by h3poteto** [comment]
Now, I don't prepare Chinese translations, so `lang="zh-"` is never specified. But if we add Chinese translations in the future, it will work.
