### ISSUE TITLE
missing app info

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1047]
There is no UI info about app version, licensing, and authors, neither.

I expected to open a modal window showing informations about the app:
 - small logo
 - app title
 - authors (also translation contributors)
 - licensing
 - download link
 - latest version status
 - app version

v. latest
OS. windows

**Comment by tassoman** [comment]
Looks like it's ignored for some OS ? (I can't understand very well)

> [Platform-specific](https://docs.rs/tauri/latest/tauri/struct.AboutMetadata.html#platform-specific)  
> Windows / macOS / Android / iOS: The metadata is ignored on these platforms.

My idea was to have a menu item near "settings" and a simple modal window.

**Comment by h3poteto** [comment]
It has been resolved in tauri v2.
