### ISSUE TITLE
[feature request] Store last Screen Position and Size

### ISSUE THREAD

**Issue by RiSK1979** [h3poteto/fedistar#1058]
I really like the client so far and it has become my main client for Mastodon so far but what is annoying on my daily use is that every time I restart the client the main window starts at another position and at a (supposedly) hard-coded window size which is very small. So I would like to ask for adding a feature to the client to store last window position and size. This should also include the window position when using a multi monitor setup.

Thank you!

**Comment by h3poteto** [comment]
@RiSK1979 Please try 1.8.1
