### ISSUE TITLE
windows version update is confusing

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1071]
When you try to install a new version on a previous version, the last must be uninstalled.  
Installation wizard takes action for you and launch uninstallation.  
Uninstallation happens but wizard doesn't think so, wrongly.  It's confusing.

New version installer can't detect older version was correctly uninstalled.

**Comment by RiSK1979** [comment]
Sorry, bur I cannot confirm that. Updating one version over another works flawlessly on my 2 Windows 10 machines.

**Comment by tassoman** [comment]
I try to investigate further my situation. Thanks for your observation.

**Comment by tassoman** [comment]
Can't reproduce in 1.7.1
