### ISSUE TITLE
Settings options are not translatable

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1182]
They came in English. (French, HighContrast .. )

**Comment by h3poteto** [comment]
You mean you want to translate this list
![Screenshot from 2023-10-01-11-24-56](https://github.com/h3poteto/fedistar/assets/4631959/04f7ea4b-4fe3-4d68-a5e7-c98a45760897)
and this list
![Screenshot from 2023-10-01-11-25-02](https://github.com/h3poteto/fedistar/assets/4631959/83fcaaf0-96d8-4b1a-af22-57df56a0c45d)
right?

**Comment by tassoman** [comment]
いいね！
