### ISSUE TITLE
Cannot post with high probability

### ISSUE THREAD

**Issue by ekfacile** [h3poteto/fedistar#1246]
**Version:** 1.7.3

## How to reproduce

1. Write the text as usual and press the post button.
2. The posted content will disappear from the text box. However, My posts don't appear on my home timeline. No error dialog is displayed either.
3. Press the reload button.
4. Posts still don't appear on my home timeline. No matter how many times I press the reload button, the result is the same.
5. Log in to the official web version for confirmation.
6. Even if you check the official website version, you can confirm that it has not been posted.
7. Check the Fedistar log file.
8. No errors are recorded in the log file.

There was no strange behavior like this until v1.7.2.

**Comment by h3poteto** [comment]
This is completely an issue on mastodon.social side. Fedistar already shows an error when a post fails.
https://github.com/h3poteto/fedistar/blob/be4926f4bf4d30dcdb6939e92116a700ea1b384d/src/components/compose/Status.tsx#L297
