### ISSUE TITLE
The latest rsuite can't use `delay` option of Whisper

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/fedistar#1272]
I can't open 
- Add new timeline button
- Emoji reaction button

---
- rsuite 5.40.0 is working
- rsuite 5.41.0 is not working

**Comment by h3poteto** [comment]
refs: https://github.com/rsuite/rsuite/issues/3490

**Comment by simonguo** [comment]
Fixed in rsuite@5.48.0

**Comment by h3poteto** [comment]
Thanks, I've already upgraded.
