### ISSUE TITLE
Not compatible with Linux Mint 20.3, Cinnamon.

### ISSUE THREAD

**Issue by expertmanofficial** [h3poteto/fedistar#1358]
One of the issues is that my OS/computer is x64 which means I can't install and open amd64 files.

Unfortunately, you don't provide for x64 Linux specifically, so please do.

**Comment by h3poteto** [comment]
Have you tried amd64.deb package?
x64 CPU means x86_64? It is completely the same as amd64 https://en.wikipedia.org/wiki/X86-64

**Comment by expertmanofficial** [comment]
@h3poteto dude, my device, OS - ISN'T amd64, that's the problem! My device doesn't supports amd64!

**Comment by h3poteto** [comment]
@expertmanofficial What kind of CPU are you using? Please tell me the exact model number.

**Comment by expertmanofficial** [comment]
Dude, I don't know. Here's my System information:

[code]
System:    Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.7 
           wm: muffin dm: LightDM Distro: Linux Mint 20.3 Una base: Ubuntu 20.04 focal 
Machine:   Type: Desktop System: LENOVO product: 3396C7U v: ThinkCentre Edge92z serial: <filter> 
           Chassis: NULL type: 3 v: NULL serial: <filter> 
           Mobo: LENOVO model: MAHOBAY v: 0B98401 PRO serial: <filter> BIOS: LENOVO v: 9XKT23AUS 
           date: 10/30/2012 
Battery:   Device-1: hidpp_battery_0 model: Logitech Wireless Keyboard serial: <filter> 
           charge: 55% (should be ignored) status: Discharging 
CPU:       Topology: Dual Core model: Intel Core i3-3220 bits: 64 type: MT MCP arch: Ivy Bridge 
           rev: 9 L2 cache: 3072 KiB 
           flags: avx lm nx pae sse sse2 sse3 sse4_1 sse4_2 ssse3 vmx bogomips: 26338 
           Speed: 3123 MHz min/max: 1600/3300 MHz Core speeds (MHz): 1: 3292 2: 3292 3: 3292 
           4: 3292 
Graphics:  Device-1: Intel Xeon E3-1200 v2/3rd Gen Core processor Graphics vendor: Lenovo 
           driver: i915 v: kernel bus ID: 00:02.0 chip ID: 8086:0152 
           Display: x11 server: X.Org 1.20.11 driver: modesetting unloaded: fbdev,vesa 
           resolution: 1920x1080~60Hz 
           OpenGL: renderer: Mesa DRI Intel HD Graphics 2500 (IVB GT1) v: 4.2 Mesa 21.0.3 
           compat-v: 3.0 direct render: Yes 
Audio:     Device-1: Intel 7 Series/C216 Family High Definition Audio vendor: Lenovo 
           driver: snd_hda_intel v: kernel bus ID: 00:1b.0 chip ID: 8086:1e20 
           Sound Server: ALSA v: k5.4.0-91-generic 
Network:   Device-1: Intel 82579LM Gigabit Network vendor: Lenovo driver: e1000e v: 3.2.6-k 
           port: f080 bus ID: 00:19.0 chip ID: 8086:1502 
           IF: enp0s25 state: down mac: <filter> 
           Device-2: Intel Centrino Wireless-N 2230 driver: iwlwifi v: kernel port: f040 
           bus ID: 02:00.0 chip ID: 8086:0888 
           IF: wlp2s0 state: up mac: <filter> 
Drives:    Local Storage: total: 476.94 GiB used: 47.77 GiB (10.0%) 
           ID-1: /dev/sda vendor: Dogfish model: SSD 512GB size: 476.94 GiB speed: 3.0 Gb/s 
           serial: <filter> 
Partition: ID-1: / size: 467.96 GiB used: 47.67 GiB (10.2%) fs: ext4 dev: /dev/sda5 
USB:       Hub: 1-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 1-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 
           chip ID: 8087:0024 
           Device-1: 1-1.3:3 info: Z-Star Micro type: Video driver: uvcvideo rev: 2.0 
           chip ID: 0ac8:c444 
           Device-2: 1-1.5:4 info: Intel type: Bluetooth driver: btusb rev: 2.0 chip ID: 8087:07da 
           Hub: 2-0:1 info: Full speed (or root) Hub ports: 2 rev: 2.0 chip ID: 1d6b:0002 
           Hub: 2-1:2 info: Intel Integrated Rate Matching Hub ports: 6 rev: 2.0 
           chip ID: 8087:0024 
           Hub: 3-0:1 info: Full speed (or root) Hub ports: 4 rev: 2.0 chip ID: 1d6b:0002 
           Device-3: 3-1:2 info: Nordic 2.4G Wireless Receiver type: Keyboard,Mouse 
           driver: hid-generic,usbhid rev: 1.1 chip ID: 25a7:fa10 
           Device-4: 3-2:3 info: Logitech Unifying Receiver type: Keyboard,Mouse 
           driver: logitech-djreceiver,usbhid rev: 2.0 chip ID: 046d:c534 
           Hub: 4-0:1 info: Full speed (or root) Hub ports: 4 rev: 3.0 chip ID: 1d6b:0003 
Sensors:   System Temperatures: cpu: 60.0 C mobo: N/A 
           Fan Speeds (RPM): N/A 
Repos:     No active apt repos in: /etc/apt/sources.list 
           Active apt repos in: /etc/apt/sources.list.d/deadsnakes-ppa-focal.list 
           1: deb http: //ppa.launchpad.net/deadsnakes/ppa/ubuntu focal main
           Active apt repos in: /etc/apt/sources.list.d/element-io.list 
           1: deb [signed-by=/usr/share/keyrings/element-io-archive-keyring.gpg] https: //packages.element.io/debian/ default main
           Active apt repos in: /etc/apt/sources.list.d/official-package-repositories.list 
           1: deb http: //packages.linuxmint.com una main upstream import backport #id:linuxmint_main
           2: deb http: //archive.ubuntu.com/ubuntu focal main restricted universe multiverse
           3: deb http: //archive.ubuntu.com/ubuntu focal-updates main restricted universe multiverse
           4: deb http: //archive.ubuntu.com/ubuntu focal-backports main restricted universe multiverse
           5: deb http: //security.ubuntu.com/ubuntu/ focal-security main restricted universe multiverse
           6: deb http: //archive.canonical.com/ubuntu/ focal partner
           Active apt repos in: /etc/apt/sources.list.d/protonvpn-stable.list 
           1: deb [signed-by=/usr/share/keyrings/protonvpn-stable-archive-keyring.gpg] https: //repo.protonvpn.com/debian stable main
           Active apt repos in: /etc/apt/sources.list.d/vivaldi.list 
           1: deb [arch=amd64] https: //repo.vivaldi.com/stable/deb/ stable main
Info:      Processes: 287 Uptime: 1h 31m Memory: 7.59 GiB used: 3.65 GiB (48.1%) Init: systemd 
           v: 245 runlevel: 5 Compilers: gcc: 9.4.0 alt: 9 Client: Unknown python3.8 client 
           inxi: 3.0.38 
[/code]

**Comment by h3poteto** [comment]
> CPU: Topology: Dual Core model: Intel Core i3-3220 bits: 64 type: MT MCP arch: Ivy Bridge
It says your CPU is 64bit, and 
> System: Kernel: 5.4.0-91-generic x86_64 bits: 64 compiler: gcc v: 9.3.0 Desktop: Cinnamon 5.2.7
You are already using x86_64 architecture OS. Therefore, your CPU architecture is amd64.
Try out amd64 package, and let me know if you have an error.

**Comment by expertmanofficial** [comment]
@h3poteto how do I know what error do I have?

**Comment by expertmanofficial** [comment]
@h3poteto  here is screen recording:


https://github.com/h3poteto/fedistar/assets/119038242/ddc7efa2-5956-4c06-985e-97d4305fd478

see? doesn't open.

**Comment by h3poteto** [comment]
Please launch Fedistar from your terminal, or please check file logs: https://fedistar.net/help
