### ISSUE TITLE
Translations are missing v 1.9.x

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1375]
Missing strings v 1.9.x

- Quit
- Minimize
- Cut
- Copy
- Paste

Emoji categories are missing translation (emoji-mart should be multilingual)

**Comment by tassoman** [comment]
I guess I was meaning the environment is Crowdin. We have that strings but no one of them is inside Crowndin.

**Comment by tassoman** [comment]
https://github.com/missive/emoji-mart/discussions/896 about emoji translations

**Comment by h3poteto** [comment]
https://github.com/tauri-apps/tauri/discussions/4985

**Comment by h3poteto** [comment]
It has been resolved in tauri v2.
