### ISSUE TITLE
Feature Request: hashtag timeline

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#1523]
As a friend noted, hashtag timeline is missing.

- As user I'd like to configure a preferred hashtag timeline so that I can read all posts about `#fedistar` found in my instance
- As user I'd like to configure an hashtag timeline, not only indicating the keyword but also indicating a "catch all" checkbox so that posts are pulled from all configured instances and listed in a column.
- As user I'd like to see from which instance is coming this post in the "catch all" "hashtag timeline"

**Hashtag timelines**

- Pleroma: https://api.pleroma.social/#operation/TimelineController.hashtag
- Mastodon: https://docs.joinmastodon.org/methods/tags/
- Gotosocial: https://github.com/superseriousbusiness/gotosocial/issues/2326

**Comment by h3poteto** [comment]
> As user I'd like to configure a preferred hashtag timeline so that I can read all posts about #fedistar found in my instance

Is it already implemented?

**Comment by tassoman** [comment]
Well, I found it. Pretty hard to understand its functionality ... I'm going to file some UX issues about it.
Thanks!
