### ISSUE TITLE
Can't open posts from the right side

### ISSUE THREAD

**Issue by iacore** [h3poteto/fedistar#1609]
It's possible to open a post from any timeline by clicking on it. However, I can't open a post from right side by clicking on it.

**Comment by h3poteto** [comment]
What do you mean?
When the right side panel is opened, you have already opened the status detail on the panel. What is the expected behavior?

**Comment by iacore** [comment]
Maybe if I click on a post in the right side panel, it should open that post's detail in the right side panel? Like recursion?

**Comment by h3poteto** [comment]
???
If you open the same status on the right side panel, you will only see the same page, right? Do you want to open the same page again? For what?

**Comment by iacore** [comment]
The same status can have replies. If I click on one of the replies, I should be able to see the reply?

**Comment by h3poteto** [comment]
Ah, I see. You mean
1. Open a status on right side panel
2. Replies are displayed on the right side panel
3. Click a status in the replies tree
4. The status detail should be opened in the right side panel <- You want to do this

Correct?

**Comment by iacore** [comment]
Yes
