### ISSUE TITLE
Version number is not visible

### ISSUE THREAD

**Issue by wadaki** [h3poteto/fedistar#1660]
The version number is not visible into the "about" windows.
Is there a plan to do this?

![grafik](https://github.com/user-attachments/assets/5a7910e3-3d60-411c-a871-2172dbcf82a3)

**Comment by h3poteto** [comment]
This is the default window of Tauri. If Tauri v2 supports the version number, we can add it. But I don't know currently.

**Comment by wadaki** [comment]
Thank you for update. In this case, I recommend for temporally case to add the product version number hard coded. Otherwise is not easy to know the installed version ;-)

**Comment by h3poteto** [comment]
I added the version in Tauri v2: https://github.com/h3poteto/fedistar/pull/1658
