### ISSUE TITLE
Doesn't launch on windows

### ISSUE THREAD

**Issue by eai04191** [h3poteto/fedistar#313]
After installing, opening the desktop or start menu shortcuts literally does nothing.

## Procedure
1. Prepare a clean Windows 11 environment (I used Windows Sandbox this time)
2. Install fedistar_0.6.0_x64_en-US.msi
3. Open the shortcut on the desktop or start menu.

## Notes
- The app does not start even on Windows which is not a virtual environment.
- I've tried several releases since 0.2.6 was released, but it has never booted successfully.
  - This means that the problem was not caused by a recent change, it was most likely not work from the beginning.
- I'm not familiar with debugging the tauri app, so I didn't know where the logs would be output. Please let me know where the logs are if I need them for debugging.
- Feel free to close this issue if it's expected that it doesn't currently work on Windows.

**Comment by h3poteto** [comment]
Please try 0.6.1: https://github.com/h3poteto/fedistar/releases/tag/v0.6.1

**Comment by eai04191** [comment]
I have confirmed that the app runs on 0.6.1. Thank you for your help.

**Comment by h3poteto** [comment]
Nice. Thank you for your reporting.
