### ISSUE TITLE
Crash when attempting to view profile from a non-signed in instance

### ISSUE THREAD

**Issue by johnvanham** [h3poteto/fedistar#392]
Steps to reproduce..

1) Sign into a mastodon instance.
2) Add a second mastodon instance without signing in.
3) Add local timeline of the second mastodon instance as a column.
4) Click on a toot.
5) Click on the user to view their profile. This is where the crash occurs.

https://user-images.githubusercontent.com/1741936/218108170-85015211-da5b-4239-ab07-c8c0c335abda.mov

Tested with codebase at commit 0905f35f08fadeb55f90c478c87271db3939411e

As well as this, it is not possible to follow, reblog or do anything with toots on instances you are not signed in to. Would it be possible for there to be a setting to set a default instance/authorization which can be used for following, reblogging, replying etc when viewing other instance feeds? Or maybe an option to select which signed-in profile to use if there is more than one? So the API request would go through your default instance instead of the instance you are not signed in to?

**Comment by h3poteto** [comment]
Thanks, I will fix this bug.

> As well as this, it is not possible to follow, reblog or do anything with toots on instances you are not signed in to.

Yes, this is the spec. These actions are not allowed in unauthorized instances.
In the future, it may be possible to implement reblogs and favorites with different accounts, but at present it is impossible. It is very very difficult because not all statuses and users are synced across all instances. If the target status does not exist on the instance, no action can be taken.

**Comment by johnvanham** [comment]
> It is very very difficult because not all statuses and users are synced across all instances. If the target status does not exist on the instance, no action can be taken.

I understand. Perhaps fedistar could check on the default signed-in instance whether the remote status/profile etc. can be found on that instance as well, if not, show a message to say it has not been possible to perform the action as the user is not signed-in? It sounds like it might be tricky but I think it would be an amazing feature.

Have you seen the Fedilab app? This is for Android but it allows you to add timelines from other instances, and you can reply, favourite, reblog and bookmark statuses from that instance. It pops up saying "Getting remote status" before it does the action. So I guess it is checking that the target status is available before it performs the action. Code is here: https://codeberg.org/tom79/Fedilab

**Comment by h3poteto** [comment]
Yeah, I know Fedilab. But if I maintain that level of functionality, maybe Fedistar will be paid app as well as Fedilab.

**Comment by johnvanham** [comment]
Seems you are pretty close though, and I think fedistar UI is much much better. And it is very fast too, I have had many columns on many instances with no slowdown at all! Everything is fast. It's a great client 👏

**Comment by h3poteto** [comment]
Hahaha, thanks.

**Comment by h3poteto** [comment]
However, I was thinking about the kind of feature you suggested from the beginning: https://medium.com/@h3poteto/im-developing-a-new-fediverse-client-application-for-desktop-fcd5b83a7ebb
> When you react to status, you can choose which account to do from…… Is it possible, I’m not sure.

**Comment by johnvanham** [comment]
> However, I was thinking about the kind of feature you suggested from the beginning: https://medium.com/@h3poteto/im-developing-a-new-fediverse-client-application-for-desktop-fcd5b83a7ebb
> 
> > When you react to status, you can choose which account to do from…… Is it possible, I’m not sure.

I found your app from this medium post :-)

**Comment by h3poteto** [comment]
I've created: #465
