### ISSUE TITLE
How to report crashes?

### ISSUE THREAD

**Issue by mars0i** [h3poteto/fedistar#441]
Hi,

Very much liking Fedistar.  Thank you gain.  It doesn't do everything I want yet--I don't expect that--but the look and feel makes it very pleasant to use.

Sometimes Fedistar has crashed (in 0.8.2 and 0.8.3--I just installed 0.8.4).  Would it be helpful to have reports about crashes?  Is there a log file I could send?  If not, that's OK, but I thought I'd ask.

**Comment by h3poteto** [comment]
Ah, thank you. I haven't sorted out how to do a crash report yet.
If you can reproduce the crash, please tell me how to reproduce it.
And logs are stored

- Linux: `~/.local/share/fedistar/fedistar.log`
- MacOS: `~/Library/Application Support/fedistar/fedistar.log`
- Windows: `~/AppData/Roaming/fedistar/fedistar.log`

**Comment by mars0i** [comment]
Thanks @h3poteto. So far, I haven't tried to reproduce crashes.   They have happened after I use fedistar for a while, so I am not sure that I can reproduce the crashes easily.  But I do think there are specific actions that helped lead to the crash.  If it happens again, I'll look at the log, and also see if I can reproduce it.
