### ISSUE TITLE
i18next translation function return invalid function instead of string

### ISSUE THREAD

**Issue by h3poteto** [h3poteto/fedistar#804]
When I call the translation function

```typescript
const { t } = useTranslation()

t("some.translation.key") // => function value() { [native code] }
```

Not always, but sometimes it happens when re-rendering.
As a result, some words are not rendered.

## Environment
OS: Manjaro Linux
Version: master

Probably it is related to #673 .
If I revert webkit2gtk, this issue is resolved.

**Comment by tassoman** [comment]
I think translation should be static inside a constant, before rendering, so that it's always available on runtime and never computed again. 
So that it just need to be read on rendering, something like `render(i18n.it.timeline_title)`

**Comment by h3poteto** [comment]
If so, when we change the translation (e.g. en -> it), the change is not reflected. We need to stop and restart the application.
