### ISSUE TITLE
Cannot send some posts / replies

### ISSUE THREAD

**Issue by ZinRicky** [h3poteto/fedistar#843]
- My server: [tilde.zone](https://tilde.zone);
- My PC’s OS: Windows 10 Home 21H2, Build 19044.2251;
- [Log file](https://github.com/h3poteto/fedistar/files/11685452/fedistar.log).

**Comment by h3poteto** [comment]
Hmm, I created an account on tilde.zone, and I tried to post from my local Fedistar. But it succeeded.
Can you reproduce it?
If you have the same error, please open devtools with "F12" key, and can you please share the error log on the devtools?

**Comment by ZinRicky** [comment]
Actually I have problems reproducing the issue. Thanks for your time
