### ISSUE TITLE
horizontal images

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#932]
Would be fine to have attachments listed in horizontal, instead vertically.
Then, having two UI arrow buttons to scroll left/right pictures.
Another behaviour can be ability to drag pictures left or right (such as actual columns dragging)

**Comment by h3poteto** [comment]
You mean you want to arrange the images in the timeline side by side, right?
![Screenshot from 2023-07-01-16-57-13](https://github.com/h3poteto/fedistar/assets/4631959/62ab2c4f-a51f-4d55-ac4b-a85630bb2b86)

> When there are more than 1 picture, maybe only the first two can be shown in the preview, using an overlay or badge indicating there are more pictures to see.

The current implementation shows previews for all images, but isn't that enough?

**Comment by tassoman** [comment]
The big deal, as you pictured, vertical images are taking lot of space. Maybe only first two can be previewed, with a +N who invites to click and slideshow one by one :thinking:

**Comment by h3poteto** [comment]
Ah, I got it.

**Comment by tassoman** [comment]
Sorry for misunderstanding, thank you!

**Comment by tassoman** [comment]
Inside v. 1.5.2 images floats left adapting to column width.  
It's OK, but when images are more than 4-6 the column stills bloated.

![immagine](https://github.com/h3poteto/fedistar/assets/92727/aaadb1b8-b76c-4479-952c-ab3077a133fd)

This is my proposal when images are more than 4

![immagine](https://github.com/h3poteto/fedistar/assets/92727/266e0668-293c-4df8-8c47-b9cfe0315f39)
