### ISSUE TITLE
Missing translation: italian

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#949]
Version 1.5.0 was supposed to include italian :it: language translation but can't be selected inside settings window.

More, sometimes translated labels disappear from the UI leaving empty buttons. Looks like happens randomly

**Comment by h3poteto** [comment]
I know it, please wait. UI side changes are not implemented yet.

**Comment by h3poteto** [comment]
> More, sometimes translated labels disappear from the UI leaving empty buttons. Looks like happens randomly

It is already reported.
https://github.com/h3poteto/fedistar/issues/804

**Comment by tassoman** [comment]
Grazie!
