### ISSUE TITLE
Applications menu, wrong position, GNU/Linux

### ISSUE THREAD

**Issue by tassoman** [h3poteto/fedistar#950]
Fedistar icon gets installed into "Development" category of GNU/Linux applications menu, should be into Internet category.  
I used `.deb` package for installation.

v. 1.5.0

**Comment by h3poteto** [comment]
https://github.com/h3poteto/fedistar/blob/14505e6a658604554fadb282706689819c5f2e39/src-tauri/tauri.conf.json#L28
