### ISSUE TITLE
Language request : fr-FR

### ISSUE THREAD

**Issue by Gyoo** [h3poteto/fedistar#978]
Hello,

I'd like to contribute by translating fedistar into french. Could you add it to Crowdin ?

**Comment by Gyoo** [comment]
French translation is done :)

**Comment by h3poteto** [comment]
Thank you.

**Comment by Gyoo** [comment]
In case updates are made, is it updated automatically ?
Just in case, I changed some strings to be more compliant with Mastodon's web UI phrasing

**Comment by h3poteto** [comment]
Yes, when you update the translation file on Crowdin, an update PR will be created automatically.
